
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQzBmeTdFYVNxZDh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeU1UTXlNVEExTXpGYUZ3MHpOREF5TVRBeU1URXdNekZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMzMEg2MGNRRXRJbzBTaHg0ajFZNzMxWGdiQ09ERTAzY3A2c2ZuZ1VlUzVDb2JPY2lQbjlKZUp5bHYKVnRNbTZkVlB2d1d5Zi9PTklkZ04zRWxJcG9EYkgwSCtrTnZhWjUrRFhXSjhkbUpmazNmSDk3Q0Jici8xRjdBRQpGb28zWWdoQm1qTE9jNllHNUNtRVpmR2xRWFMvWk1kYXk0b0R0YjZSanJPcUkvZDRYZzZFTGxjcGRXQTVoRjc5Cm55d3pUMlNQTHF4YXFPZUgyUVZqUUZ6aUtaeDR3YjV3MjlVdnpqeHFKTThyTW9WOThJSHcvYVZ5aXlkVVBjT28KTnVkMEVubTVSZlFyVG42UnJaSnkzSkRtV2NsdWtEQXdWNjdRSEdQbWJJVDNSZUQ0ZTUrcVpQRklTemZQbGVFZwpjK3R1NkhhWXRnaEJrTTJudVZuR0hURWtUeGRsQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRS1RJbE1RZnNDTkt3K3Q1MnRFbldYaUEwemFEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0lpZU5mY1BsdgpzWW9Qb21RYnBBM0NnVDMzYSttWkRRWmUyV1pqeGVlRFlZWC8yS1JHUnBQVDZ4aE12V1BEWUJzQVo2MVNXaWd4Cnh4OVR4Zi90UDFjVEdIOHFkMk9JeTVTZmVEK2R6QXptdzU0Qy9uc0VjTEswSFU0c21mV1VNNVRZT3VzYncvQTYKVS9zQVBaV0NDQlZ4MHNGSlZOQmtFV3FzZUFNQW1KM2h5OVdhZjdNTzUxZmdvVEJyc0c3WHM1Mm1jSU9aVWF5cApTUGc2WkJZclU0L2hZNExpWVhXMkN5SSszM3BYZE1mekt3cWZPYkxJeFdPL001TG5ZbTRsQmhyYmoxMk12d1RrCjdJbXV5UEUzalNYc2d1MHBpbWlNclRpMFlYZ1Vodmt6TEMxZ2tmWi9maUJpK3NjUTBZVmwySzVvUFRlM09nZ1UKakZ6M2dhTHBaY2FiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://b06081c2-3612-4d15-b200-294de639ad1c.us-lax-1.linodelke.net:443
  name: lke156404

users:
- name: lke156404-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkFCTFE3NVNldVlUZHdLYnFYMm9SUzhMbm1vdnNMWFRWZkxveEZqUW9tQncifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tOXo3NnAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNWZjOGY0NzAtMjlkNC00YTNhLTg0NzUtNmM0OWU4NjU5ODZhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.QIeuuGp51cDTz47mUztmfJDt5nwIWbmoRqK5EF191iuv9e8hv0r1DNE1JwUYSNUvPV1xU7pOuPOfMUPgJpbhCSCFV7sVAVrKB-64su-ZBJwA7phVLPyjl5M8HTB5OfnFV9udY9t7v_0vMYginemhRwutzPjdtWivDDbTDNOTYFq317OO6IXM653lsRn66kS67w7yDHgGbgzcNJlwv5sMVmUSHuKi5awhz4a6YSoP5aJKtXc34EKEiV_4hf856RcRqKgFBBqMnCixBxB5achS1Gi7W1LLMAjH6n4DE68OkZLrbtBMb5tAQMITMGKmL-cPiIJuQSOFb7P3gfcZQ2Tduw

contexts:
- context:
    cluster: lke156404
    namespace: default
    user: lke156404-admin
  name: lke156404-ctx

current-context: lke156404-ctx
